### ISSUE TITLE
Dark Theme Setting Ignored

### ISSUE THREAD

**Issue by Snaddyvitch-Dispenser** [heilig-defense/anti-fp#2]
With the plugin enabled (even if fully disabled), my operating systems theme (dark) is no longer applied to sites and all these sites that used to respect this feature now show themselves in Light Mode which is not as pleasant for me.

Even though it may lessen privacy, I would really like to be able to have dark mode enabled on websites.

**Comment by heilig-defense** [comment]
Anti-Fp does not do anything to installed themes nor should have any effect (as far as we are aware).  

And if you have it fully disabled, then no changes are made to the page.  Can you provide some screen shots so we can see exactly what you mean?

**Comment by Snaddyvitch-Dispenser** [comment]
Okay I have since looked at it, and it appears upon hard refreshing that the site no longer has a dark version of it's homepage, and the dark version was just cached. Sorry for the bother
