### ISSUE TITLE
Custom audio and canvas not working 

### ISSUE THREAD

**Issue by Alexdev577** [heilig-defense/anti-fp#3]
Audio is perfectly working with your pc software but not working with web profile builder "www.antifp.com" when I set any value it remains the same but random option is working with the web version please fix it asap.

**Comment by Alexdev577** [comment]
![Screenshot_20210628-042913_Chrome](https://user-images.githubusercontent.com/86576017/123561371-1ccf2500-d7fc-11eb-98ab-78a03ae6d338.jpg)
AudioContext Fingerprints ac-baseLatency remains the actual value of the real device please make it changeable.

**Comment by heilig-defense** [comment]
Latest update added baseLatency to spoofing and separated AudioBuffer from WebAudio.

**Comment by Alexdev577** [comment]
can you please tell me what value will make ac- baseLatency 0.004 for web
audio

**Comment by Alexdev577** [comment]
Webrtc public ip is working fine but private ip always remains the actual
fix it.
