### ISSUE TITLE
worker spoof not working

### ISSUE THREAD

**Issue by SirArya** [heilig-defense/anti-fp#4]
Hi, the extension used to be able to spoof worker information but after a recent test on creepjs, it does not seem to do that anymore, it would be nice if it could be fixed. Thank you

**Comment by heilig-defense** [comment]
Must of missed the latest CreepJs update.  @abrahamjuliot is a clever one.  We will look to see what has changed.  Thanks for letting us know.

**Comment by heilig-defense** [comment]
@SirArya The latest version (v1.2021.184.1449) updates the nested iframe spoofing which should fix the problem.
