### ISSUE TITLE
Blocking Captcha and some sites doesn't load while global is on

### ISSUE THREAD

**Issue by Thndrr** [heilig-defense/anti-fp#5]
Web.whatsapp.com doesn't load while extension is on
discord always give crashing error 
![image](https://user-images.githubusercontent.com/88783682/129040665-ae000ad5-d838-4bc1-be1f-1beb2fad1912.png)

while i was registering account at Github it wasn't accepting Captcha code.

**Comment by heilig-defense** [comment]
> Web.whatsapp.com doesn't load while extension is on
> discord always give crashing error
> ![image](https://user-images.githubusercontent.com/88783682/129040665-ae000ad5-d838-4bc1-be1f-1beb2fad1912.png)
> 
> while i was registering account at Github it wasn't accepting Captcha code.

What profile do you have set?  Did you toggle off any setting overrides to figure out what is causing it to break?  Try disabling eval and Workers and see if that works.  Those are two we generally see being problematic for some sites.

**Comment by Thndrr** [comment]
> > Web.whatsapp.com doesn't load while extension is on
> > discord always give crashing error
> > ![image](https://user-images.githubusercontent.com/88783682/129040665-ae000ad5-d838-4bc1-be1f-1beb2fad1912.png)
> > while i was registering account at Github it wasn't accepting Captcha code.
> 
> What profile do you have set? Did you toggle off any setting overrides to figure out what is causing it to break? Try disabling eval and Workers and see if that works. Those are two we generally see being problematic for some sites.

I am using free version and i haven't changed a thing, its all on default mode.. 

thanks :)
