### ISSUE TITLE
Cannot load "changes" tab on a Gitlab merge request page

### ISSUE THREAD

**Issue by levma** [heilig-defense/anti-fp#6]
When opening https://gitlab.com/:organisation_id/:project_id/-/merge_requests/:mr_id/diffs the files contents with the diffs will not show up (normally they are loaded asynchronously).

**Comment by heilig-defense** [comment]
What Anti-Fp profile do you have set?  Have you toggled any settings on or off?  Point is, every site requires some level of tuning so the site works while still providing a level of privacy obfuscation.   You'll need to figure out which setting(s) gitlab does not like and modify you profile accordingly.

**Comment by levma** [comment]
Ok, thank you! I've managed to get this site working with settings a domain profile with "minimum spoofing" for gitlab.com.
